/**
 * Simplified AI Analysis Service
 * Returns clean, readable analysis text instead of complex JSON
 */

import { GoogleGenerativeAI } from '@google/generative-ai';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || 'your-gemini-api-key';
const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);

/**
 * Generate B2C Elements of Value Analysis
 */
export async function generateB2CAnalysis(
  existing: any,
  proposed: any,
  url: string
): Promise<string> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

  const prompt = `Analyze this website using the B2C Elements of Value framework (30 consumer value elements).

URL: ${url}

EXISTING CONTENT:
- Title: ${existing.title}
- Meta Description: ${existing.metaDescription}
- Word Count: ${existing.wordCount}
- Keywords: ${existing.extractedKeywords?.slice(0, 10).join(', ') || 'None'}
- Content: ${existing.cleanText.substring(0, 1500)}

${
  proposed
    ? `
PROPOSED CONTENT:
- Title: ${proposed.title}
- Meta Description: ${proposed.metaDescription}
- Word Count: ${proposed.wordCount}
- Content: ${proposed.cleanText.substring(0, 1500)}
`
    : ''
}

B2C ELEMENTS OF VALUE FRAMEWORK (30 Elements):

FUNCTIONAL ELEMENTS (8):
- Saves Time: Does the content help users save time?
- Simplifies: Does it make complex things simple?
- Reduces Cost: Does it help users save money?
- Reduces Risk: Does it reduce uncertainty or risk?
- Organizes: Does it help organize information or processes?
- Integrates: Does it connect different systems or processes?
- Connects: Does it connect people or ideas?
- Fun/Entertainment: Is it enjoyable or entertaining?

EMOTIONAL ELEMENTS (10):
- Reduces Anxiety: Does it calm fears or worries?
- Rewards Me: Does it provide recognition or rewards?
- Nostalgia: Does it evoke positive memories?
- Design/Aesthetics: Is it visually appealing?
- Wellness: Does it promote health and well-being?
- Therapeutic Value: Does it provide emotional healing?
- Attractiveness: Does it make users feel more attractive?
- Provides Access: Does it give access to exclusive content?
- Variety: Does it offer diverse options?
- Badge Value: Does it provide status or recognition?

LIFE-CHANGING ELEMENTS (5):
- Self-Actualization: Does it help users reach their potential?
- Motivation: Does it inspire action?
- Heirloom: Does it create lasting value?
- Affiliation/Belonging: Does it create community?
- Provides Hope: Does it give optimism for the future?

SOCIAL IMPACT ELEMENTS (1):
- Self-Transcendence: Does it help users make a difference?

Please provide a comprehensive analysis in this format:

# B2C Elements of Value Analysis

## Executive Summary
[2-3 sentence overview of the content's value proposition]

## Functional Elements Analysis
**Score: X/8**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Emotional Elements Analysis  
**Score: X/10**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Life-Changing Elements Analysis
**Score: X/5**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Social Impact Analysis
**Score: X/1**
- [Analysis of self-transcendence elements]

## Overall Assessment
**Total Score: X/30**

### Strengths
- [List 3-5 key strengths]

### Opportunities
- [List 3-5 improvement opportunities]

### Recommendations
1. [Specific actionable recommendation]
2. [Specific actionable recommendation]
3. [Specific actionable recommendation]

${
  proposed
    ? `
## Comparison: Existing vs Proposed
[Compare the two versions and highlight improvements]
`
    : ''
}

---
*Analysis generated by Zero Barriers Growth Accelerator*`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('B2C Analysis error:', error);
    throw new Error('B2C Elements analysis failed');
  }
}

/**
 * Generate B2B Elements of Value Analysis
 */
export async function generateB2BAnalysis(
  existing: any,
  proposed: any,
  url: string
): Promise<string> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

  const prompt = `Analyze this website using the B2B Elements of Value framework (40 business value elements).

URL: ${url}

EXISTING CONTENT:
- Title: ${existing.title}
- Meta Description: ${existing.metaDescription}
- Word Count: ${existing.wordCount}
- Keywords: ${existing.extractedKeywords?.slice(0, 10).join(', ') || 'None'}
- Content: ${existing.cleanText.substring(0, 1500)}

${
  proposed
    ? `
PROPOSED CONTENT:
- Title: ${proposed.title}
- Meta Description: ${proposed.metaDescription}
- Word Count: ${proposed.wordCount}
- Content: ${proposed.cleanText.substring(0, 1500)}
`
    : ''
}

B2B ELEMENTS OF VALUE FRAMEWORK (40 Elements):

TABLE STAKES (4):
- Meeting Specifications: Does it meet basic requirements?
- Acceptable Price: Is pricing competitive?
- Regulatory Compliance: Does it meet legal requirements?
- Ethical Standards: Does it follow ethical practices?

FUNCTIONAL (5):
- Improved Top Line: Does it increase revenue?
- Cost Reduction: Does it reduce costs?
- Product Quality: Is the quality high?
- Scalability: Can it grow with the business?
- Innovation: Does it offer new solutions?

EASE OF DOING BUSINESS (19):
- Time Savings: Does it save time?
- Reduced Effort: Does it reduce work?
- Decreased Hassles: Does it eliminate problems?
- Information: Does it provide useful data?
- Transparency: Is it clear and honest?
- Organization: Does it organize processes?
- Simplification: Does it make things simpler?
- Connection: Does it connect systems?
- Integration: Does it integrate well?
- Availability: Is it accessible when needed?
- Variety: Does it offer options?
- Configurability: Can it be customized?
- Responsiveness: Does it respond quickly?
- Expertise: Does it provide expert knowledge?
- Commitment: Is there ongoing support?
- Stability: Is it reliable?
- Cultural Fit: Does it match company culture?
- Risk Reduction: Does it reduce business risk?
- Reach: Does it expand market reach?

INDIVIDUAL (7):
- Network Expansion: Does it grow professional networks?
- Marketability: Does it improve market position?
- Reputational Assurance: Does it enhance reputation?
- Design/Aesthetics: Is it visually appealing?
- Growth/Development: Does it promote learning?
- Reduced Anxiety: Does it reduce stress?
- Fun/Perks: Does it provide enjoyable benefits?

INSPIRATIONAL (4):
- Purpose: Does it provide clear purpose?
- Vision: Does it offer a compelling vision?
- Hope: Does it inspire optimism?
- Social Responsibility: Does it support social causes?

Please provide a comprehensive analysis in this format:

# B2B Elements of Value Analysis

## Executive Summary
[2-3 sentence overview of the content's business value proposition]

## Table Stakes Analysis
**Score: X/4**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Functional Elements Analysis
**Score: X/5**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Ease of Doing Business Analysis
**Score: X/19**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Individual Value Analysis
**Score: X/7**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Inspirational Value Analysis
**Score: X/4**
- [List present elements with evidence]
- [List missing elements with recommendations]

## Overall Assessment
**Total Score: X/40**

### Strengths
- [List 3-5 key strengths]

### Opportunities
- [List 3-5 improvement opportunities]

### Recommendations
1. [Specific actionable recommendation]
2. [Specific actionable recommendation]
3. [Specific actionable recommendation]

${
  proposed
    ? `
## Comparison: Existing vs Proposed
[Compare the two versions and highlight improvements]
`
    : ''
}

---
*Analysis generated by Zero Barriers Growth Accelerator*`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('B2B Analysis error:', error);
    throw new Error('B2B Elements analysis failed');
  }
}

/**
 * Generate CliftonStrengths Analysis
 */
export async function generateCliftonStrengthsAnalysis(
  existing: any,
  proposed: any,
  url: string
): Promise<string> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

  const prompt = `Analyze this website using the CliftonStrengths framework (34 themes across 4 domains).

URL: ${url}

EXISTING CONTENT:
- Title: ${existing.title}
- Meta Description: ${existing.metaDescription}
- Word Count: ${existing.wordCount}
- Keywords: ${existing.extractedKeywords?.slice(0, 10).join(', ') || 'None'}
- Content: ${existing.cleanText.substring(0, 1500)}

${
  proposed
    ? `
PROPOSED CONTENT:
- Title: ${proposed.title}
- Meta Description: ${proposed.metaDescription}
- Word Count: ${proposed.wordCount}
- Content: ${proposed.cleanText.substring(0, 1500)}
`
    : ''
}

CLIFTONSTRENGTHS FRAMEWORK (34 Themes):

STRATEGIC THINKING (8):
- Analytical: Seeks data and logical reasoning
- Context: Understands the past to plan the future
- Futuristic: Inspired by what could be
- Ideation: Fascinated by ideas
- Input: Collects information and resources
- Intellection: Enjoys thinking and mental activity
- Learner: Has a strong desire to learn
- Strategic: Creates alternative ways to proceed

EXECUTING (9):
- Achiever: Works hard and takes satisfaction from being busy
- Arranger: Can organize and figure out complex situations
- Belief: Has core values that are unchanging
- Consistency: Treats all people equally
- Deliberative: Takes serious care in making decisions
- Discipline: Enjoys routine and structure
- Focus: Takes direction and follows through
- Responsibility: Takes psychological ownership
- Restorative: Enjoys solving problems

INFLUENCING (8):
- Activator: Impatient for action
- Command: Has presence and can take control
- Communication: Enjoys explaining and describing
- Competition: Measures progress against others
- Maximizer: Focuses on strengths to stimulate personal and group excellence
- Self-Assurance: Confident in abilities
- Significance: Wants to be recognized and heard
- Woo: Enjoys meeting new people

RELATIONSHIP BUILDING (9):
- Adaptability: Prefers to go with the flow
- Connectedness: Believes all things happen for a reason
- Developer: Recognizes and cultivates potential in others
- Empathy: Senses the feelings of others
- Harmony: Looks for consensus
- Includer: Accepting of others
- Individualization: Intrigued by the unique qualities of each person
- Positivity: Upbeat and can get others excited
- Relator: Enjoys close relationships

Please provide a comprehensive analysis in this format:

# CliftonStrengths Analysis

## Executive Summary
[2-3 sentence overview of the content's strengths and themes]

## Strategic Thinking Domain
**Score: X/8**
- [List present themes with evidence]
- [List missing themes with recommendations]

## Executing Domain
**Score: X/9**
- [List present themes with evidence]
- [List missing themes with recommendations]

## Influencing Domain
**Score: X/8**
- [List present themes with evidence]
- [List missing themes with recommendations]

## Relationship Building Domain
**Score: X/9**
- [List present themes with evidence]
- [List missing themes with recommendations]

## Top 5 Dominant Strengths
1. [Theme name] - [Brief description and evidence]
2. [Theme name] - [Brief description and evidence]
3. [Theme name] - [Brief description and evidence]
4. [Theme name] - [Brief description and evidence]
5. [Theme name] - [Brief description and evidence]

## Overall Assessment
**Total Score: X/34**

### Strengths
- [List 3-5 key strengths]

### Opportunities
- [List 3-5 improvement opportunities]

### Recommendations
1. [Specific actionable recommendation]
2. [Specific actionable recommendation]
3. [Specific actionable recommendation]

${
  proposed
    ? `
## Comparison: Existing vs Proposed
[Compare the two versions and highlight improvements]
`
    : ''
}

---
*Analysis generated by Zero Barriers Growth Accelerator*`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('CliftonStrengths Analysis error:', error);
    throw new Error('CliftonStrengths analysis failed');
  }
}

/**
 * Generate Golden Circle Analysis
 */
export async function generateGoldenCircleAnalysis(
  existing: any,
  proposed: any,
  url: string
): Promise<string> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

  const prompt = `Analyze this website using Simon Sinek's Golden Circle framework (Why, How, What).

URL: ${url}

EXISTING CONTENT:
- Title: ${existing.title}
- Meta Description: ${existing.metaDescription}
- Word Count: ${existing.wordCount}
- Keywords: ${existing.extractedKeywords?.slice(0, 10).join(', ') || 'None'}
- Content: ${existing.cleanText.substring(0, 1500)}

${
  proposed
    ? `
PROPOSED CONTENT:
- Title: ${proposed.title}
- Meta Description: ${proposed.metaDescription}
- Word Count: ${proposed.wordCount}
- Content: ${proposed.cleanText.substring(0, 1500)}
`
    : ''
}

GOLDEN CIRCLE FRAMEWORK:

WHY (Purpose, Cause, Belief):
- What is the organization's purpose?
- What cause does it serve?
- What belief drives it?
- Why does it exist beyond making money?

HOW (Process, Methodology, Differentiation):
- How does the organization fulfill its purpose?
- What unique process or methodology does it use?
- How is it different from competitors?
- What values guide its actions?

WHAT (Products, Services, Features):
- What products or services does it offer?
- What specific features or benefits?
- What tangible things does it provide?
- What can customers buy or use?

Please provide a comprehensive analysis in this format:

# Golden Circle Analysis

## Executive Summary
[2-3 sentence overview of the content's Golden Circle alignment]

## WHY Analysis
**Score: X/10**
- **Purpose:** [Analysis of the stated purpose]
- **Cause:** [Analysis of the cause being served]
- **Belief:** [Analysis of the driving belief]
- **Emotional Connection:** [How well it connects emotionally]
- **Evidence:** [Specific examples from the content]
- **Recommendations:** [How to improve the WHY]

## HOW Analysis
**Score: X/10**
- **Process:** [Analysis of the unique process]
- **Methodology:** [Analysis of the approach]
- **Differentiation:** [How it stands out]
- **Values:** [Analysis of guiding values]
- **Evidence:** [Specific examples from the content]
- **Recommendations:** [How to improve the HOW]

## WHAT Analysis
**Score: X/10**
- **Products/Services:** [Analysis of offerings]
- **Features:** [Analysis of specific features]
- **Benefits:** [Analysis of customer benefits]
- **Clarity:** [How clear the offerings are]
- **Evidence:** [Specific examples from the content]
- **Recommendations:** [How to improve the WHAT]

## Overall Assessment
**Total Score: X/30**

### Strengths
- [List 3-5 key strengths]

### Opportunities
- [List 3-5 improvement opportunities]

### Recommendations
1. [Specific actionable recommendation]
2. [Specific actionable recommendation]
3. [Specific actionable recommendation]

${
  proposed
    ? `
## Comparison: Existing vs Proposed
[Compare the two versions and highlight improvements]
`
    : ''
}

---
*Analysis generated by Zero Barriers Growth Accelerator*`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('Golden Circle Analysis error:', error);
    throw new Error('Golden Circle analysis failed');
  }
}
