/**
 * B2C Elements of Value Analysis API
 * Uses real AI analysis and Supabase storage - NO HARDCODED FALLBACKS
 */

import { ElementsOfValueB2CService } from '@/lib/services/elements-value-b2c.service';
import { NextRequest, NextResponse } from 'next/server';
import { v4 as uuidv4 } from 'uuid';

export const maxDuration = 60; // Increased for real AI analysis

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { url, scrapedContent } = body;

    if (!url) {
      return NextResponse.json({
        success: false,
        error: 'URL is required'
      }, { status: 400 });
    }

    if (!scrapedContent) {
      return NextResponse.json({
        success: false,
        error: 'Scraped content is required'
      }, { status: 400 });
    }

    console.log(`💰 Starting REAL B2C Elements of Value analysis for: ${url}`);

    // Generate unique analysis ID
    const analysisId = uuidv4();

    // Normalize scraped content format
    let normalizedContent;
    if (typeof scrapedContent === 'string') {
      normalizedContent = {
        title: url.split('/')[2] || 'Website',
        cleanText: scrapedContent
      };
    } else {
      normalizedContent = scrapedContent;
    }

    // Run REAL AI analysis using the proper service
    const analysis = await ElementsOfValueB2CService.analyze(
      analysisId,
      normalizedContent,
      'general', // industry
      [] // patterns - will be generated by the service
    );

    console.log(`✅ REAL B2C Elements of Value analysis completed for: ${url}`);

    // Use ONLY real AI analysis data - NO HARDCODED FALLBACKS
    const frontendData = {
      overall_score: analysis.overall_score,
      functional_score: analysis.functional_score,
      emotional_score: analysis.emotional_score,
      life_changing_score: analysis.life_changing_score,
      social_impact_score: analysis.social_impact_score,
      categories: {
        functional: {
          score: analysis.functional_score,
          elements: analysis.elements
            .filter(e => e.element_category === 'functional')
            .map(e => ({
              name: e.element_name,
              score: e.score,
              evidence: e.evidence?.patterns?.join(', ') || 'No evidence found'
            }))
        },
        emotional: {
          score: analysis.emotional_score,
          elements: analysis.elements
            .filter(e => e.element_category === 'emotional')
            .map(e => ({
              name: e.element_name,
              score: e.score,
              evidence: e.evidence?.patterns?.join(', ') || 'No evidence found'
            }))
        },
        life_changing: {
          score: analysis.life_changing_score,
          elements: analysis.elements
            .filter(e => e.element_category === 'life_changing')
            .map(e => ({
              name: e.element_name,
              score: e.score,
              evidence: e.evidence?.patterns?.join(', ') || 'No evidence found'
            }))
        },
        social_impact: {
          score: analysis.social_impact_score,
          elements: analysis.elements
            .filter(e => e.element_category === 'social_impact')
            .map(e => ({
              name: e.element_name,
              score: e.score,
              evidence: e.evidence?.patterns?.join(', ') || 'No evidence found'
            }))
        }
      },
      // Use ONLY the real AI analysis data - no hardcoded calculations
      revenue_opportunities: analysis.revenue_opportunities || [],
      recommendations: analysis.recommendations || []
    };

    return NextResponse.json({
      success: true,
      url,
      data: frontendData,
      analysisId,
      message: 'B2C Elements of Value analysis completed successfully with real AI analysis'
    });

  } catch (error) {
    console.error('B2C Elements of Value API execution error:', error);
    return NextResponse.json({
      success: false,
      error: 'B2C Elements of Value analysis failed',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}
