/** Types for framework-vocabulary.json (generated by build_framework_vocabulary.py). */

export type VocabularyLevel = 'category' | 'subcategory' | 'element';

export type DefinitionSource =
  | 'archived'
  | 'archived:purpose-subcategory'
  | 'element-definitions.ts'
  | 'supplementary-element-hints.ts'
  | 'generated:value-first'
  | 'missing';

export interface VocabularySubcategory {
  subcategoryKey: string;
  subcategoryName: string;
  level: 'subcategory';
  definition: string;
  definitionSource: DefinitionSource;
  elementSlugs: string[];
}

export interface VocabularyCategory {
  frameworkKey: string;
  categoryKey: string;
  categoryName: string;
  level: 'category';
  definition: string;
  definitionSource: DefinitionSource;
  elementSlugs: string[];
  subcategories?: VocabularySubcategory[];
}

export interface VocabularyElement {
  frameworkKey: string;
  elementSlug: string;
  elementKey: string;
  displayName: string;
  level: 'element';
  definition: string;
  definitionSource: DefinitionSource;
  categoryKey: string;
  categoryName: string;
  subcategoryKey?: string;
  subcategoryName?: string;
  sortOrder: number;
}

export interface FrameworkVocabularyEntry {
  frameworkKey: string;
  frameworkName: string;
  expectedElementCount: number;
  categories: VocabularyCategory[];
  elements: VocabularyElement[];
}

export interface FrameworkVocabularyDocument {
  version: string;
  generatedAt: string;
  phase: string;
  stats: {
    totalNodes: number;
    missingDefinitions: number;
  };
  frameworks: FrameworkVocabularyEntry[];
}
